version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
  pghttpreq:
    build: .
    image: pgcron
    environment:
      PGHOST: "db"
      PGUSER: "postgres"
      LOGLEVEL: "DEBUG"
